spring:
  application:
    name: CLARIN Tool Portal UI

server:
  port: 8091

toolportal:
  search:
    primaryFacets:
      - resourceClass
      - languageCode
      - subject
    
#api:
#    client:
#        basePath: https://vlo.clarin-dev.eu/api
