spring:
  application:
    name: CLARIN Tool Portal UI

ui:
  search:
    facet-labels:
      internalResourceBundleBasenames:
        - "classpath:/messages/facetValues"
      internalMessageSourceBeanNames:
        - "languageCodeMessageSource"

#server:
#  port: 8091
#
#ui:
#  search:
#    facetValuesShown: 8
#    primaryFacets:
#      - dataProvider
#      - resourceClass
#      - toolType
#      - task
##      - Field of science/technology
#      - availability
#      - distributionType
#      - languageCode
#      - organisation
#      - projectName
#      - keywords
#    secondaryFacets:
#      - country
##      - Platform
##      - Input language
##      - Output language
##      - Annotation type
#  facet-labels:
#    resourceBundleBasenames:
#      - "file:/my/custom/resourceBundle"
    
#api:
#    client:
#        basePath: https://vlo.clarin-dev.eu/api
